{"name": "test_forgotpassword_invalid_otp1_error", "status": "passed", "attachments": [{"name": "stdout", "source": "bf55f88f-37b4-4eee-aae7-426f5ffff4eb-attachment.txt", "type": "text/plain"}], "start": 1757781334195, "stop": 1757781345062, "uuid": "2a6ed535-5017-4ced-9ebc-68b7e25827bd", "historyId": "6ec9ad9310dcc6217263c941384037c4", "testCaseId": "6ec9ad9310dcc6217263c941384037c4", "fullName": "tests.test_forgotpassword#test_forgotpassword_invalid_otp1_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_forgotpassword"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "54724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_forgotpassword"}]}