{"name": "test_forgotpassword_resend_function", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == 'SUCCESS'", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"2d7e7884011c8090999084a27db77ec5\")>\n\n    @pytest.mark.usefixtures(\"driver\")\n    def test_forgotpassword_resend_function(driver):\n        driver.get(config[\"base_url\"])\n        captch_url= config[\"captch_url\"]\n        username = config[\"forgotpassword\"][\"email_5times\"]\n        forgotpass = Forgotpassword(driver)\n        forgotpass.click_forgot_password_link()\n        forgotpass.create_username(username)\n        forgotpass.click_continue_button()\n        print(\"waiting for 30 sec\")\n        time.sleep(31)\n        forgotpass.click_resend_otp_link()\n        time.sleep(3)\n        forgotpass.capture_otp(username,captch_url)\n        title, message = forgotpass.get_toast_message()\n>       assert title == \"SUCCESS\"\nE       AssertionError: assert None == 'SUCCESS'\n\ntests\\test_forgotpassword.py:132: AssertionError"}, "attachments": [{"name": "stdout", "source": "0f37422f-aa4c-4d95-8542-7b74025f40bf-attachment.txt", "type": "text/plain"}], "start": 1757581996906, "stop": 1757582071100, "uuid": "5a5fe1d9-21fd-4ae0-8d4c-554a4c15e62b", "historyId": "fe726bcfc909283923f1299e44bd99dd", "testCaseId": "fe726bcfc909283923f1299e44bd99dd", "fullName": "tests.test_forgotpassword#test_forgotpassword_resend_function", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_forgotpassword"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "87552-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_forgotpassword"}]}