{"name": "test_forgotpassword_resend_function", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == 'SUCCESS'", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"64fd552ae233d7741985de70050ff916\")>\n\n    @pytest.mark.usefixtures(\"driver\")\n    def test_forgotpassword_resend_function(driver):\n        driver.get(config[\"base_url\"])\n        captch_url= config[\"captch_url\"]\n        username = config[\"forgotpassword\"][\"email_5times\"]\n        forgotpass = Forgotpassword(driver)\n        forgotpass.click_forgot_password_link()\n        forgotpass.create_username(username)\n        forgotpass.click_continue_button()\n        print(\"waiting for 30 sec\")\n        time.sleep(31)\n        forgotpass.click_resend_otp_link()\n        time.sleep(3)\n        forgotpass.capture_otp(username,captch_url)\n        title, desc = forgotpass.get_toast_message()\n>       assert title == \"SUCCESS\"\nE       AssertionError: assert None == 'SUCCESS'\n\ntests\\test_forgotpassword.py:132: AssertionError"}, "attachments": [{"name": "stdout", "source": "0c5b1991-6ab4-4dea-9e1d-d2d6e5818f7f-attachment.txt", "type": "text/plain"}], "start": 1757589672691, "stop": 1757589754026, "uuid": "a9a72b40-84f8-4c18-b8be-186a77f50a44", "historyId": "fe726bcfc909283923f1299e44bd99dd", "testCaseId": "fe726bcfc909283923f1299e44bd99dd", "fullName": "tests.test_forgotpassword#test_forgotpassword_resend_function", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_forgotpassword"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "85756-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_forgotpassword"}]}