{"name": "test_forgotpassword_resend_function", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == 'SUCCESS'", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"11fe2d22f1f3245923d9d5a7238953af\")>\n\n    @pytest.mark.usefixtures(\"driver\")\n    def test_forgotpassword_resend_function(driver):\n        driver.get(config[\"base_url\"])\n        captch_url= config[\"captch_url\"]\n        username = config[\"forgotpassword\"][\"email_5times\"]\n        forgotpass = Forgotpassword(driver)\n        forgotpass.click_forgot_password_link()\n        forgotpass.create_username(username)\n        forgotpass.click_continue_button()\n        print(\"waiting for 30 sec\")\n        time.sleep(31)\n        forgotpass.click_resend_otp_link()\n        time.sleep(3)\n        forgotpass.capture_otp(username,captch_url)\n        title, desc = forgotpass.get_toast_message()\n>       assert title == \"SUCCESS\"\nE       AssertionError: assert None == 'SUCCESS'\n\ntests\\test_forgotpassword.py:132: AssertionError"}, "attachments": [{"name": "stdout", "source": "4a0d3e90-834f-462c-8a01-45335827fb47-attachment.txt", "type": "text/plain"}], "start": 1757584737822, "stop": 1757584810102, "uuid": "108e47b2-b614-4658-a51b-b9323e68d8a2", "historyId": "fe726bcfc909283923f1299e44bd99dd", "testCaseId": "fe726bcfc909283923f1299e44bd99dd", "fullName": "tests.test_forgotpassword#test_forgotpassword_resend_function", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_forgotpassword"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "83120-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_forgotpassword"}]}