{"name": "test_forgotpassword_invalid_otp2_error", "status": "passed", "attachments": [{"name": "stdout", "source": "6106856e-b288-420a-8dc2-7d9eba4b7680-attachment.txt", "type": "text/plain"}], "start": 1757351583564, "stop": 1757351584270, "uuid": "bc6915ed-9b39-443d-afe2-24b47a9f48ae", "historyId": "96f12f8efb93948b1bf032b478771881", "testCaseId": "96f12f8efb93948b1bf032b478771881", "fullName": "tests.test_forgotpassword#test_forgotpassword_invalid_otp2_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_forgotpassword"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "60208-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_forgotpassword"}]}