{"name": "test_existing_email_validation_error", "status": "passed", "attachments": [{"name": "stdout", "source": "d01cd58b-fb5a-437d-8dbc-3452eeb53afb-attachment.txt", "type": "text/plain"}], "start": 1758043127122, "stop": 1758043145981, "uuid": "96f3b352-e0b6-43c7-a3f4-80890184a9c7", "historyId": "2b3ceebf8361f2e5776dee9405d6d919", "testCaseId": "2b3ceebf8361f2e5776dee9405d6d919", "fullName": "tests.test_my_team#test_existing_email_validation_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_my_team"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "84860-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_my_team"}]}