{"name": "test_forgotpassword_invalid_otp_Attempts_more_than_5times_error", "status": "passed", "attachments": [{"name": "stdout", "source": "08480a07-ba8d-4541-a11b-40a64627d131-attachment.txt", "type": "text/plain"}], "start": 1757781510429, "stop": 1757781524597, "uuid": "0dd78eee-93e6-403e-a2c4-9668c7da752d", "historyId": "e95dace5e6a248cf98a6a329369d40fc", "testCaseId": "e95dace5e6a248cf98a6a329369d40fc", "fullName": "tests.test_forgotpassword#test_forgotpassword_invalid_otp_Attempts_more_than_5times_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_forgotpassword"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "54724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_forgotpassword"}]}