{"name": "test_forgotpassword_invalid_otp2_error", "status": "passed", "attachments": [{"name": "stdout", "source": "3400722a-bbaf-4d00-b89b-7ed16e49ee0a-attachment.txt", "type": "text/plain"}], "start": 1757781345071, "stop": 1757781345977, "uuid": "8f9c7667-4787-468c-a195-f8df33e94f36", "historyId": "96f12f8efb93948b1bf032b478771881", "testCaseId": "96f12f8efb93948b1bf032b478771881", "fullName": "tests.test_forgotpassword#test_forgotpassword_invalid_otp2_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_forgotpassword"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "54724-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_forgotpassword"}]}