{"name": "test_forgotpassword_resend_function", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == 'SUCCESS'", "trace": "driver = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"65c1fb633d0238a3f6a0b3d2b486a122\")>\n\n    @pytest.mark.usefixtures(\"driver\")\n    def test_forgotpassword_resend_function(driver):\n        driver.get(config[\"base_url\"])\n        captch_url= config[\"captch_url\"]\n        username = config[\"forgotpassword\"][\"email_5times\"]\n        forgotpass = Forgotpassword(driver)\n        forgotpass.click_forgot_password_link()\n        forgotpass.create_username(username)\n        forgotpass.click_continue_button()\n        print(\"waiting for 30 sec\")\n        time.sleep(31)\n        forgotpass.click_resend_otp_link()\n        time.sleep(3)\n        forgotpass.capture_otp(username,captch_url)\n        title, description = forgotpass.get_toast_message()\n>       assert title == \"SUCCESS\"\nE       AssertionError: assert None == 'SUCCESS'\n\ntests\\test_forgotpassword.py:132: AssertionError"}, "attachments": [{"name": "stdout", "source": "30f4a542-abf2-4f88-b200-c45b8f7065f4-attachment.txt", "type": "text/plain"}], "start": 1757585648002, "stop": 1757585721396, "uuid": "fe98d8d1-b177-4444-a87a-979049a00822", "historyId": "fe726bcfc909283923f1299e44bd99dd", "testCaseId": "fe726bcfc909283923f1299e44bd99dd", "fullName": "tests.test_forgotpassword#test_forgotpassword_resend_function", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_forgotpassword"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "78952-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_forgotpassword"}]}