{"name": "test_correct_username_incorrect_password_validation_error", "status": "passed", "attachments": [{"name": "stdout", "source": "047ce3a8-a498-44e5-bcf2-2f8d4d4ae613-attachment.txt", "type": "text/plain"}], "start": 1757606262524, "stop": 1757606265003, "uuid": "e020a4e2-9337-4b3c-8ea8-e19a2594c498", "historyId": "e930212584cd195ca9e6b77f0c71884f", "testCaseId": "e930212584cd195ca9e6b77f0c71884f", "fullName": "tests.test_login#test_correct_username_incorrect_password_validation_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "50024-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}