{"name": "test_existing_email_validation_error", "status": "passed", "attachments": [{"name": "stdout", "source": "f30114a5-dc32-4660-8d1e-446510371c12-attachment.txt", "type": "text/plain"}], "start": 1757309875617, "stop": 1757309888627, "uuid": "2d34befb-53ad-44b1-8075-4f9611954f4e", "historyId": "2b3ceebf8361f2e5776dee9405d6d919", "testCaseId": "2b3ceebf8361f2e5776dee9405d6d919", "fullName": "tests.test_my_team#test_existing_email_validation_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_my_team"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "95380-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_my_team"}]}