{"name": "test_existing_email_validation_error", "status": "passed", "attachments": [{"name": "stdout", "source": "1068a5f0-6ecb-4e8c-8943-7a36762b1662-attachment.txt", "type": "text/plain"}], "start": 1757323257497, "stop": 1757323270057, "uuid": "60a0c379-bcfe-49eb-a495-00bbf8a5fef7", "historyId": "2b3ceebf8361f2e5776dee9405d6d919", "testCaseId": "2b3ceebf8361f2e5776dee9405d6d919", "fullName": "tests.test_my_team#test_existing_email_validation_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_my_team"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "88428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_my_team"}]}