{"name": "test_signup_set_num_validation_error", "status": "passed", "attachments": [{"name": "stdout", "source": "4cfe2033-099c-416b-8ae0-228202b84bf2-attachment.txt", "type": "text/plain"}], "start": 1757693395149, "stop": 1757693397659, "uuid": "cd7f1f2e-01cf-48e4-aa50-3e29332e6fd7", "historyId": "1d10b2d394593f82c3bfff023d08e63e", "testCaseId": "1d10b2d394593f82c3bfff023d08e63e", "fullName": "tests.test_signup#test_signup_set_num_validation_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_signup"}, {"name": "host", "value": "OTSI-Lap80"}, {"name": "thread", "value": "76776-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_signup"}]}